# ==========================
# Configuração Global
# ==========================

client_max_body_size 20m;
error_page 400 /errors/400.html;
error_page 403 /errors/403.html;
error_page 404 /errors/404.html;
error_page 405 /errors/405.html;
error_page 408 /errors/408.html;
error_page 413 /errors/413.html;
error_page 500 /errors/500.html;
error_page 501 /errors/501.html;
error_page 502 /errors/502.html;
error_page 503 /errors/503.html;
error_page 504 /errors/504.html;
error_page 505 /errors/505.html;
# ==========================
# Primeiro Servidor (localhost:8080)
# ==========================

server {
    listen 127.0.0.1:8080;
    listen 0.0.0.0:8081;
    root ./www/robusto/server1;
    index index.html index.htm;

    location / {
        # autoindex on;
        #allow_methods GET POST;
    }

    location /upload {
        #allow_methods POST GET;
        autoindex on;
        upload_enabled on;
        index upload.html;
        root ./www/robusto/server1/api/upload;
        upload_path ./www/robusto/server1/api/upload;
    }

    location /api {
        #allow_methods POST;
        autoindex on;
        root ./www/robusto/server1/api;
    }
    location /redirect {
        root ./www/robusto/server1/redirect;
        allow_methods GET;
        return 301 http://localhost:8080/teste;
    }

    location /teste {
        root ./www/robusto/server1/teste;
        index index_ts.html;
    }

    location /cgi {
        root ./www/robusto/server1/api/test;
        index index_cgi.html;
        allow_methods GET POST DELETE;
        upload_enabled on;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }

    location /cgi-bin {
        root ./www/robusto/server1/api/cgi;
        index index_cgi.html;
        allow_methods GET POST DELETE;
        upload_enabled on;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
    location /bonus {
        root ./www/bonus;
        index landing.html;
    }
    location /login
    {
        root ./www/bonus;
        index uploadtest.html;
    }
    location /dashboard 
    {
        root ./www/bonus;
        index homepage.html;
    }
}

# ==========================
# Segundo Servidor (127.0.0.1:8080)
# ==========================

server {
    listen 0.0.0.0:3003;
    root ./www/robusto/server2;
    index index.html;
    client_max_body_size 2M;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /admin {
        index admin.html;
        root ./www/robusto/server2/admin;
    }
    location /documents {
        index index.html;
        root ./www/robusto/server2/docs;
    }
    location /images {
        index index.html;
        root ./www/robusto/server2/images;
    }
    location /templates {
        root ./www/robusto/server2/templates;
        index empty_state.html;
        upload_enabled on;
        upload_path ./www/robusto/server2/uploads;
    }
    location /upload {
        index index.html;
        upload_enabled on;
        upload_path ./www/robusto/server2/upload;
        root ./www/robusto/server2/upload;
    }
    location /uploads {
        root ./www/robusto/server2;
        index upload_form.html;
        upload_enabled on;
        upload_path ./www/robusto/server2/uploads;
    }
}

# ==========================
# Terceiro Servidor (0.0.0.0:9090)
# ==========================

server {
    listen 0.0.0.0:9090;
    root ./www/robusto/server3;
    index index.html;

    location / {
        allow_methods GET POST DELETE;
    }

    location /data {
        allow_methods GET POST;
        index upload.html;
        upload_enabled on;
        upload_path ./www;
#        return 413 ;
    }
    location /cgi-sh
    {
        cgi_ext .sh;
        cgi_path /usr/bin/sh;
        root ./www/robusto/server3;
    }
}
