error_page 400 /errors/400.html;
error_page 403 /errors/403.html;
error_page 404 /errors/404.html;
error_page 405 /errors/405.html;
error_page 408 /errors/408.html;
error_page 413 /errors/413.html;
error_page 500 /errors/500.html;
error_page 501 /errors/501.html;
error_page 502 /errors/502.html;
error_page 503 /errors/503.html;
error_page 504 /errors/504.html;
error_page 505 /errors/505.html;
client_max_body_size 15M;

server
{
    listen 5000;
    root ./www/templates/html5up-paradigm-shift;
    index index.html;
}

server 
{
    listen 5001;
    root ./www/templates/templatemo_588_ebook_landing;
    index index.html;
}

server 
{
    listen 5002;
    root ./www/templates/templatemo_600_prism_flux;
    index index.html;
}

server
{
    listen 5003;
    root ./www/templates/templatemo_603_nexaverse;
    index index.html;
}