error_page 400 /errors/400.html;
error_page 403 /errors/403.html;
error_page 404 /errors/404.html;
error_page 405 /errors/405.html;
error_page 408 /errors/408.html;
error_page 413 /errors/413.html;
error_page 500 /errors/500.html;
error_page 501 /errors/501.html;
error_page 502 /errors/502.html;
error_page 503 /errors/503.html;
error_page 504 /errors/504.html;
error_page 505 /errors/505.html;
client_max_body_size 15M;

server {
    listen 2005;
    root ./www/test_autoindex;
    
    index index.html index.htm test.html;
    
    # Location raiz com autoindex desabilitado (procura index)
    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }
    
    # Location com autoindex habilitado
    location /test_dir {
    	root ./www/test_autoindex/test_dir;
        allow_methods GET;
        autoindex on;
    }
    
    # Location para uploads com autoindex
    location /api {
    	root ./www/test_autoindex/api;
        allow_methods GET POST DELETE;
        autoindex on;
        upload_path ./www/test_autoindex/api/upload;
    }
}
