server {
    listen 80;;
    server_name;
    root /var/www/html extra;
    index index.html;
    location /assets {
        root /var/www/assets;
        index index.html index2.html;
    }
}

#Error