http {
    server {
        listen 80;
        server_name example.com;
        location /images {
            root /var/www/images;
            index index.html index.html;
        }
        location /videos {
            root /var/www/videos;
        }
        server {
            listen 8080;
        }
    }
}

#Error